<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NSubstitute" Version="6.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniiaAnonim.TGBot.Api\UniiaAnonim.TGBot.Api.csproj" />
    <ProjectReference Include="..\UniiaAnonim.TGBot.Domain\UniiaAnonim.TGBot.Domain.csproj" />
    <ProjectReference Include="..\UniiaAnonim.TGBot.Infrastructure\UniiaAnonim.TGBot.Infrastructure.csproj" />
    <ProjectReference Include="..\UniiaAnonim.TGBot.Services\UniiaAnonim.TGBot.Application.csproj" />
    <ProjectReference Include="..\UniiaAnonim.TGBot.Shared\UniiaAnonim.TGBot.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UnitTests\Infrastructure\Repositories\" />
  </ItemGroup>

</Project>