using System.Net.Mime;
using System.Text.Json;
using Microsoft.Extensions.Diagnostics.HealthChecks;

namespace UniiaAnonim.TGBot.Api.HealthChecks;

/// <summary>
/// Provides custom response writing logic for health check endpoints.
/// </summary>
public static class HealthCheckResponseWriter
{
    private static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);

    /// <summary>
    /// Writes the health check report as a structured JSON response.
    /// </summary>
    /// <param name="context">The HTTP context of the current request.</param>
    /// <param name="report">The health report generated by the health check service.</param>
    /// <returns>A task that represents the asynchronous write operation.</returns>
    public static async Task WriteJsonResponse(HttpContext context, HealthReport report)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(report);

        context.Response.ContentType = MediaTypeNames.Application.Json;

        var response = new
        {
            Status = report.Status.ToString(),
            TotalDuration = report.TotalDuration.ToString(),
            Checks = report.Entries.Select(e => new
            {
                Name = e.Key,
                Status = e.Value.Status.ToString(),
                Duration = e.Value.Duration.ToString(),
                e.Value.Description,
                Error = e.Value.Exception?.Message,
            }),
        };

        await JsonSerializer.SerializeAsync(context.Response.Body, response, SerializerOptions);
    }
}