// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniiaAnonim.TGBot.Infrastructure.Persistence;

#nullable disable

namespace UniiaAnonim.TGBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniiaAnonim.TGBot.Domain.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("UniiaAnonim.TGBot.Domain.Models.StoryAuthor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthorIdHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ChannelMessageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthorIdHash");

                    b.ToTable("StoryAuthor");
                });

            modelBuilder.Entity("UniiaAnonim.TGBot.Domain.Models.StoryFileEntity", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("StoryId", "FileId");

                    b.ToTable("StoryFileEntity");
                });

            modelBuilder.Entity("UniiaAnonim.TGBot.Domain.Models.StoryFileEntity", b =>
                {
                    b.HasOne("UniiaAnonim.TGBot.Domain.Models.StoryAuthor", "StoryAuthor")
                        .WithMany("StoryMessages")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoryAuthor");
                });

            modelBuilder.Entity("UniiaAnonim.TGBot.Domain.Models.StoryAuthor", b =>
                {
                    b.Navigation("StoryMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
